
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Get a list of the policy metadata resources.
.Description
Get a list of the policy metadata resources.
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyMetadata
.Link
https://learn.microsoft.com/powershell/module/az.policyinsights/get-azpolicymetadata
#>
function Get-AzPolicyMetadata {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyMetadata])]
[CmdletBinding(DefaultParameterSetName='List', PositionalBinding=$false)]
param(
    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.Int32]
    # Maximum number of records to return.
    ${Top},

    [Parameter()] #parameters previous: ParameterSetName='Get', Mandatory
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # The name of the policy metadata resource.
    ${Name},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The DefaultProfile parameter is not functional.
    # Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    ${DefaultProfile},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

# Future pass:
# - separate Top and Name parameter sets? ... pretty sure they're mutually exclusive lol
# - implement partial class of list class so that we can implement overrideOnOk and check if 'Top' amount has been returned!!! 

process {

    $output = $null

    if($PSBoundParameters.ContainsKey("Name"))
    {
        # remove Name from the PSBoundParameters, add ResourceName to the PSBoundParameters and call Get-AzPolicyMetadataResource
        $null = $PSBoundParameters.Remove("Name")
        $null = $PSBoundParameters.Add("ResourceName", $Name)
        $output = Az.PolicyInsights.internal\Get-AzPolicyMetadataResource @PSBoundParameters
    } 
    elseif($PSBoundParameters.ContainsKey("Top"))
    {
        $output = Az.PolicyInsights.internal\Get-AzPolicyMetadata @PSBoundParameters

        # there's a chance that additional metadata were returned so ensuring that only the 'Top' amount are there
        $output = $output | select -First $Top 

        # now cast from Slim type to full 
        $output = $output | ForEach-Object { [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.PolicyMetadata] $_ }
    }
    else
    {
        $output = Az.PolicyInsights.internal\Get-AzPolicyMetadata @PSBoundParameters

        # now cast from Slim type to full
        $output = $output | ForEach-Object { [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.PolicyMetadata] $_ }
    }

    $PSCmdlet.WriteObject($output, $true)
    }
}