
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Queries policy states for the resources under the management group.
.Description
Queries policy states for the resources under the management group.
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Outputs
Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyState
.Link
https://learn.microsoft.com/powershell/module/az.policyinsights/get-azpolicystate
#>
function Get-AzPolicyState {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyState])]
[CmdletBinding(DefaultParameterSetName='List1', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(ParameterSetName='List', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Management group name.
    ${ManagementGroupName},

    [Parameter(ParameterSetName='List1')]
    [Parameter(ParameterSetName='List2')]
    [Parameter(ParameterSetName='List4')]
    [Parameter(ParameterSetName='List5')]
    [Parameter(ParameterSetName='List6')]
    [Parameter(ParameterSetName='List7')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String[]]
    # Microsoft Azure subscription ID.
    ${SubscriptionId},

    [Parameter(ParameterSetName='List2', Mandatory)]
    [Parameter(ParameterSetName='List7', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Resource group name.
    ${ResourceGroupName},

    [Parameter(ParameterSetName='List3', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Resource ID.
    ${ResourceId},

    [Parameter(ParameterSetName='List4', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Policy set definition name.
    ${PolicySetDefinitionName},

    [Parameter(ParameterSetName='List5', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Policy definition name.
    ${PolicyDefinitionName},

    [Parameter(ParameterSetName='List6', Mandatory)]
    [Parameter(ParameterSetName='List7', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Policy assignment name.
    ${PolicyAssignmentName},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.String]
    # OData apply expression for aggregations.
    ${Apply},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.String]
    # OData filter expression.
    ${Filter},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.DateTime]
    # ISO 8601 formatted timestamp specifying the start time of the interval to query.
    # When not specified, the service uses ($to - 1-day).
    ${From},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.String]
    # Ordering expression using OData notation.
    # One or more comma-separated column names with an optional "desc" (the default) or "asc", e.g.
    # "$orderby=PolicyAssignmentId, ResourceId asc".
    ${OrderBy},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.String]
    # Select expression using OData notation.
    # Limits the columns on each record to just those requested, e.g.
    # "$select=PolicyAssignmentId, ResourceId".
    ${Select},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.DateTime]
    # ISO 8601 formatted timestamp specifying the end time of the interval to query.
    # When not specified, the service uses request time.
    ${To},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.Int32]
    # Maximum number of records to return.
    ${Top},

    [Parameter(ParameterSetName='List3')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Query')]
    [System.String]
    # The $expand query parameter.
    # For example, to expand components use $expand=components
    ${Expand},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The DefaultProfile parameter is not functional.
    # Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    ${DefaultProfile},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.Management.Automation.SwitchParameter]
    # Get all states, not just the latest.
    ${All},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

# customization required to:
# - rename cmdlet to Get-AzPolicyState
# - use a SwitchParameter 'All' to determine how to set PolicyStatesResource when calling the internal cmdlet
# - removing the SkipToken parameter

process {
    
    if($PSBoundParameters.ContainsKey("All"))
    {
        $null = $PSBoundParameters.Remove("All")
        $null = $PSBoundParameters.Add("PolicyStatesResource", "default")
        Az.PolicyInsights.internal\Get-AzPolicyStateQueryResult @PSBoundParameters
    }
    else
    {
        $null = $PSBoundParameters.Remove("All")
        $null = $PSBoundParameters.Add("PolicyStatesResource", "latest")
        Az.PolicyInsights.internal\Get-AzPolicyStateQueryResult @PSBoundParameters
    }

    }
}