# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

using namespace System.Management.Automation.Language

# split scope into usable parts
function ParseScope {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param($scope)

    # validate args
    if (!$scope) {
        throw 'ParseScope(scope) argument error: scope must be provided.'
    }

    # Remove leading slash if there, conflicts with generated code
    $scope = $scope.TrimStart('/')

    $scopeType = ''
    $subId = ''
    $mgName = ''
    $rgName = ''
    $resource = ''
    $resNamespace = ''
    $resType = ''
    $resName = ''

    # check for likeness and extract useful values
    if (($scope -like 'providers/Microsoft.Management/managementGroups/*') -or ($scope -like 'Microsoft.Management/managementGroups/*') -or ($scope -like 'managementGroups/*')) {
        $scopeType = 'mgname'
        $mgName = ($scope -split 'managementGroups/')[1]
    }
    elseif ($scope -like 'subscriptions/*/resourceGroups/*/*') {
        $scopeType = 'resource'
        $temp = ($scope -split 'subscriptions/')[1]
        $temp = ($temp -split '/resourceGroups/')
        $subId = $temp[0]
        $temp = ($temp[1] -split '/providers/')
        $rgName = $temp[0]
        $temp = $temp[1] -split '/'
        if ($temp.Length -gt 2) {
            $resNamespace = $temp[0]
            $resType = $temp[1..($temp.Length-2)] -join '/'
            $resName = $temp[$temp.Length-1]
        }

        $resource = $scope
    }
    elseif ($scope -like 'subscriptions/*/resourceGroups/*') {
        $scopeType = 'rgname'
        $temp = ($scope -split 'subscriptions/')[1]
        $temp = ($temp -split '/resourceGroups/')
        $subId = $temp[0]
        $rgName = $temp[1]
    }
    elseif ($scope -like 'subscriptions/*') {
        $scopeType = 'subId'
        $subId = ($scope -split 'subscriptions/')[1]
    }
    else {
        throw 'Improper scope provided. Please change format.'
    }

    return @{
        Scope = $scope
        ScopeType = $scopeType
        SubscriptionId = $subId
        ManagementGroupName = $mgName
        ResourceGroupName = $rgName
        ResourceName = $resName
        Resource = $resource
        ResourceNamespace = $resNamespace
        ResourceType = $resType
    }
}

# convert various parameter input formats to policy-formatted hashtable suitable for autorest serializers
function ConvertParameterInput
{
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param ($InputObject)

    # traverse collections to ensure nested values are all processed
    if ($InputObject -is [hashtable]) {
        $returnValue = @{}
        foreach ($key in $InputObject.Keys) {
            $returnValue[$key] = (ConvertParameterInput $InputObject[$key])
        }

        return $returnValue
    }
    elseif ($InputObject -is [array]) {
        $returnValue = @()
        foreach ($object in $InputObject) {
            $returnValue += (ConvertParameterInput $object)
        }

        return ,$returnValue
    }
    elseif ($InputObject -is [PSObject])
    {
        $returnValue = @{}
        foreach ($property in $InputObject.PSObject.Properties) {
            $returnValue[$property.Name] = (ConvertParameterInput $property.Value)
        }

        return $returnValue
    }
    else {
        return $InputObject
    }
}

# Wrapper for JSON -> PSObject conversion that works on both Core and Desktop editions
function ConvertFrom-JsonSafe
{
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param(
        [Parameter(ValueFromPipeline)]
        $InputObject,
        [switch]$AsHashtable = $false
    )

    if ($PSVersionTable.PSEdition -eq 'Core') {
        ConvertFrom-Json $InputObject -AsHashtable:$AsHashtable
    }
    elseif ($AsHashtable) {
        # ConvertFrom-Json on Windows Powershell doesn't support -AsHashtable parameter
        $converted = ConvertParameterInput ($InputObject | ConvertFrom-Json)
        if (($converted -is [array]) -and ($converted.Count -eq 1)) {
            return $converted[0]
        }
        else {
            return $converted
        }
    }
    else {
        ConvertFrom-Json $InputObject
    }
}

# tests whether the given string is a Uri
function Test-Uri {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param([string]$Value)

    $uri = ''
    [System.Uri]::TryCreate($Value, [System.UriKind]::Absolute, [ref]$uri)
}

# issues a GET to the given address and returns the contents
function Get-UriContent {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param([string]$UriAddress)

    $response = Invoke-WebRequest $UriAddress -DisableKeepAlive -Method Get
    if ($response.StatusCode -eq 200) {
        return $response.Content
    }
}

# if the given string is a file path or URI, returns the contents of the file or web page
# otherwise returns the original string
function GetFileUriOrStringParameterValue {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param([string]$parameterValue)

    if (Test-Path $parameterValue) {
        Get-Content $parameterValue | Out-String
    }
    else {
        if (Test-Uri $parameterValue) {
            Get-UriContent $parameterValue
        }
        else {
            $parameterValue
        }
    }
}

# Recursive conversion function for common AST blocks from parsing
function Convert-AstLiteral {
    param([Ast] $Node)
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]

    switch ($Node) {
        # Strings like "text" or 'text'
        { $_.GetType() -eq [StringConstantExpressionAst] } { return $_.Value }
        { $_.GetType() -eq [ExpandableStringExpressionAst] } { return $_.Value } # unexpanded, by design
        # Numbers, $true/$false/$null
        { $_.GetType() -eq [ConstantExpressionAst] } { return $_.Value }
        # This node type is essentially a wrapper node for an array
        { $_.GetType() -eq [ArrayExpressionAst] } {
            $arr = @()
            foreach ($e in $_.SubExpression.Statements) {
                $arr += Convert-AstLiteral $e
            }
            return $arr
        }
        # Arrays: @( ... )
        { $_.GetType() -eq [ArrayLiteralAst] } {
            $arr = @()
            foreach ($e in $_.Elements) {
                $arr += Convert-AstLiteral $e
            }
            return $arr
        }
        # Nested hashtables 
        { $_.GetType() -eq [HashtableAst] } {
            $h = @{}
            foreach ($kv in $_.KeyValuePairs) {
                $k = $kv.Item1.Value
                $h[$k] = Convert-AstLiteral $kv.Item2
            }
            return $h
        }
        # Case where a literal is wrapped in a pipeline
        { $_.GetType() -eq [PipelineAst] } {
            if ($_.PipelineElements.Count -eq 1) {
                return Convert-AstLiteral $_.PipelineElements[0].Expression
            }
            else {
                throw "Ran into issue attempting to parse PSCustomObject."
            }
        }
        # Handles variables such as $null, $true, $false
        { $_.GetType() -eq [VariableExpressionAst] } {
            if ($_.VariablePath.IsVariable) {
                return $_.VariablePath.UserPath
            }
            else {
                throw "Unsupported variable path for safe conversion: $($_.VariablePath.ToString()). Unable to parse PSCustomObject."
            }
        }
        default {
            # Anything else is not allowed
            throw "Unsupported AST node for safe conversion: $($_.GetType().Name). Unable to parse PSCustomObject."
        }
    }
}

# Safely converts a string representation of a hashtable or PSCustomObject into a hashtable
function ConvertTo-HashtableSafely {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param(
        [Parameter(Mandatory)]
        [string] $InputObject
    )

    $tokens = $null; $errors = $null
    $ast = [Parser]::ParseInput($InputObject, [ref]$tokens, [ref]$errors)

    if ($errors?.Count) {
        throw "Invalid PSCustomObject or hashtable literal: $($errors[0].Message)"
    }

    # Find the first expression in the script
    $expr = $ast.EndBlock.Statements | ForEach-Object {
        $_.PipelineElements | ForEach-Object { $_.Expression }
    } | Select-Object -First 1

    if (-not ($expr -is [HashtableAst])) {
        throw "Top-level expression is not a hashtable."
    }

    return Convert-AstLiteral $expr
}

# Returns metadata property as hashtable, extracting from file when necessary
function ResolvePolicyMetadataParameter {
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.DoNotExportAttribute()]
    param(
        $MetadataValue,
        [bool]$Debug = $false
    )

    if ($metadataValue -is [hashtable]) {
        return $metadataValue
    }

    if ([System.String]::IsNullOrEmpty($metadataValue)) {
        return $metadataValue
    }

    $metadata = (GetFileUriOrStringParameterValue $metadataValue).Trim()
    if ($debug) {
        Write-Host -ForegroundColor Cyan Metadata: $metadata
    }

    if ($metadata -like '@{*') {
        # probably a PSCustomObject, try converting to hashtable
        return ConvertTo-HashtableSafely -InputObject $metadata
    }

    # otherwise it should be a JSON string
    if ($metadata -like '{*}') {
        return $metadata | ConvertFrom-JsonSafe -AsHashtable
    }

    throw "Unrecognized metadata format - value: [$($metadataValue)], type: [$($metadataValue.GetType())]"
}