
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Create a remediation at management group scope.
.Description
Create a remediation at management group scope.
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Inputs
Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyInsightsIdentity
.Outputs
Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IRemediation
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

INPUTOBJECT <IPolicyInsightsIdentity>: Identity Parameter
  [AttestationName <String>]: The name of the attestation.
  [AuthorizationNamespace <String>]: The namespace for Microsoft Authorization resource provider; only "Microsoft.Authorization" is allowed.
  [Id <String>]: Resource identity path
  [ManagementGroupId <String>]: Management group ID.
  [ManagementGroupName <String>]: Management group name.
  [ManagementGroupsNamespace <String>]: The namespace for Microsoft Management RP; only "Microsoft.Management" is allowed.
  [NextLink <String>]: Next link for list operation.
  [PolicyAssignmentName <String>]: Policy assignment name.
  [PolicyDefinitionName <String>]: Policy definition name.
  [PolicyEventsResource <String>]: The name of the virtual resource under PolicyEvents resource type; only "default" is allowed.
  [PolicySetDefinitionName <String>]: Policy set definition name.
  [PolicyStatesResource <String>]: The virtual resource under PolicyStates resource type. In a given time range, 'latest' represents the latest policy state(s), whereas 'default' represents all policy state(s).
  [PolicyStatesSummaryResource <String>]: The virtual resource under PolicyStates resource type for summarize action. In a given time range, 'latest' represents the latest policy state(s) and is the only allowed value.
  [RemediationName <String>]: The name of the remediation.
  [ResourceGroupName <String>]: The name of the resource group. The name is case insensitive.
  [ResourceId <String>]: Resource ID.
  [ResourceName <String>]: The name of the policy metadata resource.
  [SubscriptionId <String>]: The ID of the target subscription.
.Link
https://learn.microsoft.com/powershell/module/az.policyinsights/start-azpolicyremediation
#>
function Start-AzPolicyRemediation {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IRemediation])]
[CmdletBinding(DefaultParameterSetName='CreateExpanded1', PositionalBinding=$false, ConfirmImpact='Medium')]
param(
    [Parameter(ParameterSetName='CreateExpanded', Mandatory)]
    [Parameter(ParameterSetName='CreateExpandedScope')]
    [Alias('ManagementGroupName')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Management group ID.
    ${ManagementGroupId},

    [Parameter(ParameterSetName='CreateExpanded', Mandatory)]
    [Parameter(ParameterSetName='CreateExpanded1', Mandatory)]
    [Parameter(ParameterSetName='CreateExpanded2', Mandatory)]
    [Parameter(ParameterSetName='CreateExpanded3', Mandatory)]
    [Parameter(ParameterSetName='CreateExpandedScope', Mandatory)]
    [Parameter(ParameterSetName='CreateViaIdentityManagementGroupExpanded', Mandatory)]
    [Alias('RemediationName')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # The name of the remediation.
    ${Name},

    [Parameter(ParameterSetName='CreateExpanded1')]
    [Parameter(ParameterSetName='CreateExpanded2')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String]
    # The ID of the target subscription.
    ${SubscriptionId},

    [Parameter(ParameterSetName='CreateExpanded2', Mandatory)]
    [Parameter(ParameterSetName='CreateExpandedScope')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Resource group name.
    ${ResourceGroupName},

    [Parameter(ParameterSetName='CreateExpanded3', Mandatory)]
    [Alias('Id')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [System.String]
    # Resource ID.
    ${ResourceId},

    [Parameter(ParameterSetName='CreateViaIdentityExpanded1', Mandatory, ValueFromPipeline)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Models.IPolicyInsightsIdentity]
    # Identity Parameter
    ${InputObject},

    [Parameter()]
    [Alias('FailureThreshold')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.Single]
    # A number between 0.0 to 1.0 representing the percentage failure threshold.
    # The remediation will fail if the percentage of failed remediation operations (i.e.
    # failed deployments) exceeds this threshold.
    ${FailureThresholdPercentage},

    [Parameter()]
    [AllowEmptyCollection()]
    [Alias('LocationFilter')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.String[]]
    # The resource locations that will be remediated.
    ${FilterLocation},

    [Parameter()]
    [AllowEmptyCollection()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.String[]]
    # The IDs of the resources that will be remediated.
    # Can specify at most 100 IDs.
    # This filter cannot be used when ReEvaluateCompliance is set to ReEvaluateCompliance, and cannot be empty if provided.
    ${FilterResourceId},

    [Parameter()]
    [Alias('ParallelDeploymentCount')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.Int32]
    # Determines how many resources to remediate at any given time.
    # Can be used to increase or reduce the pace of the remediation.
    # If not provided, the default parallel deployments value is used.
    ${ParallelDeployment},

    [Parameter(ParameterSetName='CreateExpanded')]
    [Parameter(ParameterSetName='CreateExpanded1')]
    [Parameter(ParameterSetName='CreateExpanded2')]
    [Parameter(ParameterSetName='CreateExpanded3')]
    [Parameter(ParameterSetName='CreateExpandedScope', Mandatory)]
    [Parameter(ParameterSetName='CreateViaIdentityExpanded1')]
    [Parameter(ParameterSetName='CreateViaIdentityExpanded2')]
    [Parameter(ParameterSetName='CreateViaIdentityExpanded3')]
    [Parameter(ParameterSetName='CreateViaIdentityManagementGroupExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.String]
    # The resource ID of the policy assignment that should be remediated.
    ${PolicyAssignmentId},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.String]
    # The policy definition reference ID of the individual definition that should be remediated.
    # Required when the policy assignment being remediated assigns a policy set definition.
    ${PolicyDefinitionReferenceId},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.Int32]
    # Determines the max number of resources that can be remediated by the remediation job.
    # If not provided, the default resource count is used.
    ${ResourceCount},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.PSArgumentCompleterAttribute("ExistingNonCompliant", "ReEvaluateCompliance")]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Body')]
    [System.String]
    # The way resources to remediate are discovered.
    # Defaults to ExistingNonCompliant if not specified.
    ${ResourceDiscoveryMode},

    [Parameter(ParameterSetName='CreateExpandedScope', Mandatory)]
    [System.String]
    # Scope of the resource. E.g. '/subscriptions/{subscriptionId}/resourceGroups/{rgName}'.
    ${Scope},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run cmdlet in the background. Runs until terminal state of Remediation is reached.
    ${AsJob},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Run the command asynchronously
    ${NoWait},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The DefaultProfile parameter is not functional.
    # Use the SubscriptionId parameter when available if executing the cmdlet against a different subscription.
    ${DefaultProfile},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.PolicyInsights.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

# okay! changes were pushed from this working branch
# so now we can fuck it up! lmao 
# but fr, just wanna see if there's a way to make this work without fully removing this params :)

process {

    # Generated code can't parse which scope of InputObject is being passed in so it's easiest to parse it into other parameters 
    if($PSBoundParameters.ContainsKey("InputObject"))
    {        
        # extract scope from the InputObject's Id and add to Parameters 
        $idSplit = $InputObject.Id -split '/providers/microsoft.policyinsights/remediations/'
        $null = $PSBoundParameters.Add("Scope", $idSplit[0])
        $null = $PSBoundParameters.Add("Name", $idSplit[1])

        # remove the InputObject parameter
        $null = $PSBoundParameters.Remove("InputObject")
    }

    # pre process the "Scope" parameter into other parameters if it's present
    if($PSBoundParameters.ContainsKey("Scope"))
    {
        # processing the Scope parameter with a helper method
        $Scope = $PSBoundParameters["Scope"] 
        $scopeObject = ParseScope $Scope 

        switch ($scopeObject.ScopeType) {
            'mgname' {
                $null = $PSBoundParameters.Add("ManagementGroupId", $scopeObject.ManagementGroupName)
            }
            'rgname' {
                $null = $PSBoundParameters.Add("SubscriptionId", $scopeObject.SubscriptionId)
                $null = $PSBoundParameters.Add("ResourceGroupName", $scopeObject.ResourceGroupName)
            }
            'subId' {
                $null = $PSBoundParameters.Add("SubscriptionId", $scopeObject.SubscriptionId)
            }
            'resource' {

                $null = $PSBoundParameters.Add("ResourceId", $scopeObject.Resource)
            }
            default {
                throw "The provided scope '$Scope' is not valid for this cmdlet. Supported scopes are management group, resource group, subscription, and resource."
            }
        }

        $null = $PSBoundParameters.Remove("Scope")
    }

    # Check if AsJob switch was used and setup a job to run and call the cmdlet within it
    if($PSBoundParameters.ContainsKey("AsJob"))
    {
        $null = $PSBoundParameters.Remove("AsJob")

        # Remove HTTP pipeline parameters that can't be serialized
        $nonSerializableParams = @('HttpPipelinePrepend', 'HttpPipelineAppend', 'Break')
        foreach ($param in $nonSerializableParams) {
            if ($PSBoundParameters.ContainsKey($param)) {
                $null = $PSBoundParameters.Remove($param)
            }
        }

        # Save context to a temp file for the job to import
        $contextFilePath = [System.IO.Path]::GetTempFileName()
        $null = Save-AzContext -Path $contextFilePath -Force

        # ScriptBlock for Start-Job to call, it does the necessary env setup required to run the cmdlet in a fresh powershell process
        $scriptCmd = {
            param($InputParameters, $ScriptRoot, $ContextFilePath)

            # Load the main module which handles Az.Accounts integration and proper initialization
            $mainModulePath = Join-Path $ScriptRoot '..\Az.PolicyInsights.psd1'
            if(Test-Path $mainModulePath) {
                $null = Import-Module -Name $mainModulePath -Force
            }

            # Restore the Azure context in the job
            $null = Import-AzContext -Path $ContextFilePath

            # Clean up the temp file
            Remove-Item -Path $ContextFilePath -Force -ErrorAction SilentlyContinue

            & Start-AzPolicyRemediation @InputParameters
        }

        $parametersHashtable = [hashtable]$PSBoundParameters

        $output = Start-Job -ScriptBlock $scriptCmd -ArgumentList $parametersHashtable, $PSScriptRoot, $contextFilePath

        return $output
    }

    # if NoWait is present, call the internal cmdlet and return that output immediately
    if($PSBoundParameters.ContainsKey("NoWait"))
    {
        $null = $PSBoundParameters.Remove("NoWait")
        $output = Az.PolicyInsights.internal\New-AzPolicyRemediation @PSBoundParameters
        $PSCmdlet.WriteObject($output, $true)
        return
    }

    # since NoWait isn't present, we'll start the remediation and poll it until it's reached a terminal state
    $remediation = Az.PolicyInsights.internal\New-AzPolicyRemediation @PSBoundParameters

    # setup dictionary of scope and name parameters to use for Get
    $scopeKeys = @('ResourceGroupName', 'SubscriptionId', 'ResourceId', 'ManagementGroupId')
    $scopeParams = @{}
    foreach ($key in $scopeKeys) {
        if ($PSBoundParameters.ContainsKey($key)) {
            $scopeParams[$key] = $PSBoundParameters[$key]
        }
    }
    $scopeParams['Name'] = $Name

    $remediationStatus = $remediation.ProvisioningState
    $terminalStates = @("Succeeded", "Failed", "Canceled", "Complete")

    # Polling loop to check if remediation has finished
    while ($remediationStatus -inotin $terminalStates)
    {
        Write-Debug "Delay between polling calls. Current remediation status: '$remediationStatus'. Waiting for 30 seconds before checking again..."
        Start-Sleep -Seconds 30

        # Call Get-AzPolicyRemediation to check the status again
        $remediation = Get-AzPolicyRemediation @scopeParams
        $remediationStatus = $remediation.ProvisioningState
    }

    $output = $remediation

    $PSCmdlet.WriteObject($output, $true)

    # Resetting modified/added parameters in case multiple objects are piped in
    $PSBoundParameters.Clear()
}
}